### ISSUE TITLE
Steamvr 2.0 update breaking changes?

### ISSUE THREAD

**Issue by compieter-gh** [DevOculus-Meta-Quest/OculusKiller#2]
With the new steamvr 2.0 update i have been having issues where if i use OculessKiller and go into Any game my controllers dont work.
switching back too OculusDash fixes it.
Am i the only one who is having this issue? And what should i do?

**Comment by noahlessard** [comment]
There is a steamvr beta that fixes this issue. It will probably get integrated into a full patch soon, but you should be able to fix it now super easy by going to Properties > Betas -> select SteamVR beta update. Should be V 2.0.9

**Comment by Eliminater74** [comment]
I am marking this as Closed, Since SteamVR Beta 2.0.9 fixes the issue..
