### ISSUE TITLE
 Getting back to the old version

### ISSUE THREAD

**Issue by Anonymo** [DevOculus-Meta-Quest/OculusKiller#5]
How do you revert to an older version? I want to go back to the Original SteamVR v.1.x.

**Comment by Eliminater74** [comment]
goto Lib, search for your SteamVR App, click on it, click the settings gear thing on the right.. then click Manage app,
then click beta, and remove your self from beta by choosing none..
then close it all and it will download the standard edition..

**Comment by Anonymo** [comment]
Oh man, that's too hard.  I'll probably just throw this thing away.
